from turtle import *
import shapes

# GOOFY function
# Draws Goofy starting from the top left corner of a tile
# (do not change code)
#
def draw_goofy():
    # Background
    setheading(0)
    forward(shapes.single)
    right(shapes.angle)
    forward(5)
    shapes.draw_star('darkorange', 35)
    setheading(shapes.angle)
    forward(5)
    setheading(180)
    forward(shapes.single)

    # Hat
    setheading(0)
    forward(75)
    right(shapes.angle)
    forward(35)
    setheading(150)
    color('#000000') # black
    pendown()
    width(2)
    fillcolor('yellow green')
    begin_fill()
    forward(15)
    setheading(60)
    circle(5, 180)
    setheading(160)
    forward(10)
    setheading(70)
    circle(5, 230)
    setheading(240)
    forward(5)
    setheading(170)
    circle(5, 230)
    setheading(340)
    forward(10)
    setheading(250)
    circle(5, 180)
    setheading(320)
    forward(15)
    end_fill()
    penup()
    setheading(180)
    forward(18)
    right(shapes.angle)
    forward(12)
    setheading(60)
    pendown()
    width(7)
    forward(17)
    penup()

    # Head
    setheading(0)
    forward(10)
    right(shapes.angle)
    forward(40)
    setheading(0)
    fillcolor('#000000') # black
    begin_fill()
    shapes.draw_oval(30)
    end_fill()
    setheading(0)
    forward(40)
    setheading(shapes.angle)
    forward(10)
    setheading(120)
    begin_fill()
    shapes.draw_oval(20)
    end_fill()
    setheading(0)
    forward(15)
    setheading(shapes.angle)
    forward(5)
    setheading(120)
    begin_fill()
    shapes.draw_oval(20)
    end_fill()

    # Eyes
    fillcolor('#FFFFFF') # white
    setheading(120)
    begin_fill()
    shapes.draw_oval(16, 5)
    end_fill()
    setheading(180)
    forward(10)
    setheading(270)
    forward(5)
    setheading(120)
    begin_fill()
    shapes.draw_oval(16, 5)
    end_fill()
    fillcolor('#000000') # black
    setheading(120)
    begin_fill()
    shapes.draw_oval(6, 2)
    end_fill()
    setheading(0)
    forward(10)
    left(shapes.angle)
    forward(5)
    setheading(120)
    begin_fill()
    shapes.draw_oval(6, 2)
    end_fill()

    # Mouth
    setheading(180)
    forward(5)
    setheading(270)
    forward(22)
    fillcolor('bisque')
    setheading(50)
    begin_fill()
    shapes.draw_oval(15)
    end_fill()
    setheading(0)
    forward(12)
    setheading(shapes.angle)
    forward(3)
    setheading(50)
    begin_fill()
    shapes.draw_oval(15)
    end_fill()
    setheading(0)
    forward(12)
    setheading(270)
    forward(2)
    setheading(50)
    begin_fill()
    shapes.draw_oval(20)
    end_fill()
    setheading(0)
    forward(10)
    setheading(shapes.angle)
    forward(7)
    setheading(30)
    begin_fill()
    shapes.draw_oval(15, 5)
    end_fill()
    setheading(180)
    forward(35)
    setheading(280)
    begin_fill()
    circle(20, 180)
    end_fill()
    setheading(180)
    forward(40)
    setheading(270)
    forward(5)
    setheading(170)
    begin_fill()
    shapes.draw_oval(15, 5)
    end_fill()

    # Lips
    setheading(180)
    forward(15)
    setheading(shapes.angle)
    forward(1)
    setheading(325)
    pendown()
    width(2)
    color('#000000') # black
    circle(40, 80)
    setheading(310)
    circle(10, 70)
    penup()

    # Nose
    setheading(shapes.angle)
    forward(13)
    left(shapes.angle)
    forward(7)
    fillcolor('#000000') # black
    setheading(80)
    begin_fill()
    shapes.draw_oval(10)
    end_fill()

    # Teeth
    setheading(270)
    forward(15)
    pendown()
    fillcolor('#FFFFFF') # white
    begin_fill()
    forward(3)
    setheading(10)
    forward(5)
    setheading(shapes.angle)
    forward(4)
    end_fill()
    penup()
    setheading(180)
    forward(20)
    setheading(270)
    forward(7)
    pendown()
    begin_fill()
    forward(3)
    setheading(180)
    forward(5)
    right(shapes.angle)
    forward(2)
    end_fill()

    # Wrinkles
    penup()
    forward(25)
    setheading(0)
    forward(5)
    pendown()
    setheading(200)
    circle(25, 35)
    penup()
    setheading(shapes.angle)
    forward(5)
    pendown()
    setheading(200)
    circle(25, 35)
    penup()

    # Ears
    setheading(270)
    forward(5)
    setheading(180)
    forward(50)
    pendown()
    width(7)
    setheading(240)
    forward(10)
    setheading(230)
    width(8.5)
    forward(10)
    setheading(210)
    width(10)
    forward(20)
    setheading(200)
    width(11.5)
    forward(20)
    penup()
    setheading(0)
    forward(70)
    left(shapes.angle)
    forward(25)
    pendown()
    setheading(240)
    width(7)
    forward(12)
    setheading(230)
    width(8.5)
    forward(9)
    setheading(210)
    width(10)
    forward(8)

    # Resets back to default drawing values
    fillcolor('#000000') # black
    color('#000000') # black
    width(1)
    penup()
